=== navikt/modiapersonoversikt-api/consumer/src/main/resources/xml/xsd/prioritetT.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>

    <!-- Schema vi referer til -->
    <xs:include schemaLocation="fellesTyper.xsd"/>
    <xs:include schemaLocation="fagomrade.xsd"/>

    <!-- Hovedkodeliste med relasjoner -->
    <xs:element name="prioritetTListe" type="prioritetTListeType">
        <xs:unique name="UnikePrioritetTKode">
            <xs:selector xpath="./prioritetT"/>
            <xs:field xpath="@kode"/>
        </xs:unique>
        <xs:key name="prioritetTFagomradeKode">
            <xs:selector xpath="./fagomradeListe/fagomrade"/>
            <xs:field xpath="@kode"/>
        </xs:key>
        <xs:keyref refer="prioritetTFagomradeKode" name="prioritetTFagomradeKodeRef">
            <xs:selector xpath="./prioritetT"/>
            <xs:field xpath="@fagomrade"/>
        </xs:keyref>
    </xs:element>
    <xs:complexType name="prioritetTListeType">
        <xs:sequence>
            <xs:element name="fagomradeListe" type="fagomradeListeType"/>
            <xs:element name="prioritetT" type="prioritetTType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="xml:base"/>
    </xs:complexType>

    <!-- Hoved kodetype -->
    <xs:complexType name="prioritetTType">
        <xs:complexContent>
            <xs:extension base="felleskodeType">
                <xs:sequence>
                    <xs:element name="gosys" type="gosysprioritetTType" minOccurs="0"/>
                    <xs:element name="gsak" type="gsakprioritetTType" minOccurs="0"/>
                    <xs:element name="ruting" type="rutingprioritetTType" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="dekode" type="string_200" use="required"/>
                <xs:attribute name="fagomrade" type="string_20" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Systemspesifke typer -->
    <xs:complexType name="gosysprioritetTType">
        <xs:attribute name="dekode" type="string_200" use="optional"/>
        <xs:attribute name="datoFom" type="xs:date" use="optional"/>
        <xs:attribute name="datoTom" type="xs:date" use="optional"/>
        <xs:attribute name="datoOpprettet" type="xs:dateTime" use="optional"/>
        <xs:attribute name="opprettetAv" type="string_20" use="optional"/>
        <xs:attribute name="endretAv" type="string_20" use="optional"/>
        <xs:attribute name="erGyldig" type="xs:boolean" use="optional"/>
        <xs:attribute name="fagomrade" type="string_20" use="optional"/>
        <xs:attribute name="kode" type="string_20" use="optional"/>
    </xs:complexType>

    <xs:complexType name="gsakprioritetTType">
        <xs:attribute name="dekode" type="string_200" use="optional"/>
        <xs:attribute name="datoFom" type="xs:date" use="optional"/>
        <xs:attribute name="datoTom" type="xs:date" use="optional"/>
        <xs:attribute name="datoOpprettet" type="xs:dateTime" use="optional"/>
        <xs:attribute name="opprettetAv" type="string_20" use="optional"/>
        <xs:attribute name="endretAv" type="string_20" use="optional"/>
        <xs:attribute name="erGyldig" type="xs:boolean" use="optional"/>
        <xs:attribute name="fagomrade" type="string_20" use="optional"/>
        <xs:attribute name="kode" type="string_40" use="optional"/>
    </xs:complexType>

    <xs:complexType name="rutingprioritetTType">
        <xs:attribute name="dekode" type="string_200" use="optional"/>
        <xs:attribute name="datoFom" type="xs:date" use="optional"/>
        <xs:attribute name="datoTom" type="xs:date" use="optional"/>
        <xs:attribute name="datoOpprettet" type="xs:dateTime" use="optional"/>
        <xs:attribute name="opprettetAv" type="string_20" use="optional"/>
        <xs:attribute name="endretAv" type="string_20" use="optional"/>
        <xs:attribute name="erGyldig" type="xs:boolean" use="optional"/>
        <xs:attribute name="fagomrade" type="string_20" use="optional"/>
        <xs:attribute name="prioritetT" type="string_20" use="optional"/>
    </xs:complexType>

</xs:schema>

=== navikt/modiapersonoversikt-api/consumer/src/main/resources/xml/prioritetT.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="kodeverkView.xsl"?>
<prioritetTListe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude"
                 xsi:noNamespaceSchemaLocation="xsd/prioritetT.xsd">
    <xi:include href="fagomrade.xml"/>
    <prioritetT kode="HOY" datoFom="2007-11-16" datoOpprettet="2007-11-16T13:50:40" dekode="Høy" endretAv="ukjent" erGyldig="true" fagomrade="PEN" opprettetAv="ukjent" gosys="true" gsak="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2007-11-16T13:50:40" endretAv="ukjent" kode="HOY" opprettetAv="ukjent"/>
    </prioritetT>
    <prioritetT kode="HOY_AAP" datoFom="2010-02-13" datoOpprettet="2010-02-13T03:18:01" dekode="Høy" endretAv="KAA2812" erGyldig="true" fagomrade="AAP" opprettetAv="KAA2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" kode="HOY_AAP"/>
        <gsak datoOpprettet="2010-02-13T03:18:01" kode="HOY_AAP"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" prioritetT="HOY_AAP"/>
    </prioritetT>
    <prioritetT kode="HOY_AAR" datoFom="2010-10-02" datoOpprettet="2010-10-02T04:21:04" dekode="Høy" endretAv="KAA2812" erGyldig="true" fagomrade="AAR" opprettetAv="KAA2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" kode="HOY_AAR"/>
        <gsak datoOpprettet="2010-10-02T04:21:04" kode="HOY_AAR"/>
        <ruting datoOpprettet="2010-12-07T21:39:39" prioritetT="HOY_AAR"/>
    </prioritetT>
    <prioritetT kode="HOY_AGR" datoFom="2010-10-02" datoOpprettet="2010-10-02T04:21:04" dekode="Høy" endretAv="KAA2812" erGyldig="true" fagomrade="AGR" opprettetAv="KAA2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" kode="HOY_AGR"/>
        <gsak datoOpprettet="2010-10-02T04:21:04" kode="HOY_AGR"/>
        <ruting datoOpprettet="2010-12-07T21:39:39" prioritetT="HOY_AGR"/>
    </prioritetT>
    <prioritetT kode="HOY_BAR" datoFom="2008-09-16" datoOpprettet="2008-09-16T01:03:58" dekode="Høy" endretAv="kaa2812" erGyldig="true" fagomrade="BAR" opprettetAv="kaa2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_BAR" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2008-09-16T01:03:58" endretAv="kaa2812" kode="HOY_BAR" opprettetAv="kaa2812"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" endretAv="KAA2812" opprettetAv="KAA2812" prioritetT="HOY_BAR"/>
    </prioritetT>
    <prioritetT kode="HOY_BID" datoFom="2007-11-16" datoOpprettet="2007-11-16T13:50:40" dekode="Høy" endretAv="ukjent" erGyldig="true" fagomrade="BID" opprettetAv="ukjent" gosys="true" gsak="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_BID" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2007-11-16T13:50:40" endretAv="ukjent" kode="HOY_BID" opprettetAv="ukjent"/>
    </prioritetT>
    <prioritetT kode="HOY_BII" datoFom="2008-10-03" datoOpprettet="2008-10-03T09:59:44" dekode="Høy" endretAv="NAV9999" erGyldig="true" fagomrade="BII" opprettetAv="NAV9999" gosys="true" gsak="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_BII" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2008-10-03T09:59:44" endretAv="NAV9999" kode="HOY_BII" opprettetAv="NAV9999"/>
    </prioritetT>
    <prioritetT kode="HOY_BIL" datoFom="2008-09-16" datoOpprettet="2008-09-16T01:03:58" dekode="Høy" endretAv="kaa2812" erGyldig="true" fagomrade="BIL" opprettetAv="kaa2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_BIL" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2008-09-16T01:03:58" endretAv="kaa2812" kode="HOY_BIL" opprettetAv="kaa2812"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" endretAv="KAA2812" opprettetAv="KAA2812" prioritetT="HOY_BIL"/>
    </prioritetT>
    <prioritetT kode="HOY_DAG" datoFom="2009-04-25" datoOpprettet="2009-04-25T04:43:20" dekode="Høy" endretAv="Joachim L" erGyldig="true" fagomrade="DAG" opprettetAv="Joachim L" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_DAG" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2009-04-25T04:43:20" endretAv="Joachim L" kode="HOY_DAG" opprettetAv="Joachim L"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" endretAv="KAA2812" opprettetAv="KAA2812" prioritetT="HOY_DAG"/>
    </prioritetT>
    <prioritetT kode="HOY_ENF" datoFom="2008-09-16" datoOpprettet="2008-09-16T01:03:58" dekode="Høy" endretAv="kaa2812" erGyldig="true" fagomrade="ENF" opprettetAv="kaa2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_ENF" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2008-09-16T01:03:58" endretAv="kaa2812" kode="HOY_ENF" opprettetAv="kaa2812"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" endretAv="KAA2812" opprettetAv="KAA2812" prioritetT="HOY_ENF"/>
    </prioritetT>
    <prioritetT kode="HOY_ERS" datoFom="2009-04-25" datoOpprettet="2009-04-25T04:43:20" dekode="Høy" endretAv="Joachim L" erGyldig="true" fagomrade="ERS" opprettetAv="Joachim L" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_ERS" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2009-04-25T04:43:20" endretAv="Joachim L" kode="HOY_ERS" opprettetAv="Joachim L"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" endretAv="KAA2812" opprettetAv="KAA2812" prioritetT="HOY_ERS"/>
    </prioritetT>
    <prioritetT kode="HOY_FEI" datoFom="2010-02-13" datoOpprettet="2010-02-13T03:18:01" dekode="Høy" endretAv="KAA2812" erGyldig="true" fagomrade="FEI" opprettetAv="KAA2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" kode="HOY_FEI"/>
        <gsak datoOpprettet="2010-02-13T03:18:01" kode="HOY_FEI"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" prioritetT="HOY_FEI"/>
    </prioritetT>
    <prioritetT kode="HOY_FOR" datoFom="2008-09-16" datoOpprettet="2008-09-16T01:03:58" dekode="Høy" endretAv="kaa2812" erGyldig="true" fagomrade="FOR" opprettetAv="kaa2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_FOR" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2008-09-16T01:03:58" endretAv="kaa2812" kode="HOY_FOR" opprettetAv="kaa2812"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" endretAv="KAA2812" opprettetAv="KAA2812" prioritetT="HOY_FOR"/>
    </prioritetT>
    <prioritetT kode="HOY_FOS" datoFom="2009-02-05" datoOpprettet="2009-02-05T21:37:00" dekode="Høy" endretAv="KAA2812" erGyldig="true" fagomrade="FOS" opprettetAv="KAA2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" kode="HOY_FOS"/>
        <gsak datoOpprettet="2009-02-05T21:37:00" kode="HOY_FOS"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" prioritetT="HOY_FOS"/>
    </prioritetT>
    <prioritetT kode="HOY_FUL" datoFom="2010-02-13" datoOpprettet="2010-02-13T03:18:01" dekode="Høy" endretAv="KAA2812" erGyldig="true" fagomrade="FUL" opprettetAv="KAA2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" kode="HOY_FUL"/>
        <gsak datoOpprettet="2010-02-13T03:18:01" kode="HOY_FUL"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" prioritetT="HOY_FUL"/>
    </prioritetT>
    <prioritetT kode="HOY_GEN" datoFom="2010-02-13" datoOpprettet="2010-02-13T03:11:53" dekode="Høy" endretAv="KAA2812" erGyldig="true" fagomrade="GEN" opprettetAv="KAA2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" kode="HOY_GEN"/>
        <gsak datoOpprettet="2010-02-13T03:11:53" kode="HOY_GEN"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" prioritetT="HOY_GEN"/>
    </prioritetT>
    <prioritetT kode="HOY_GRA" datoFom="2008-09-16" datoOpprettet="2008-09-16T01:03:58" dekode="Høy" endretAv="kaa2812" erGyldig="true" fagomrade="GRA" opprettetAv="kaa2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_GRA" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2008-09-16T01:03:58" endretAv="kaa2812" kode="HOY_GRA" opprettetAv="kaa2812"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" endretAv="KAA2812" opprettetAv="KAA2812" prioritetT="HOY_GRA"/>
    </prioritetT>
    <prioritetT kode="HOY_GRU" datoFom="2008-09-16" datoOpprettet="2008-09-16T01:03:58" dekode="Høy" endretAv="kaa2812" erGyldig="true" fagomrade="GRU" opprettetAv="kaa2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_GRU" opprettetAv="KAA2812"/>
        <gsak datoOpprettet="2008-09-16T01:03:58" endretAv="kaa2812" kode="HOY_GRU" opprettetAv="kaa2812"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" endretAv="KAA2812" opprettetAv="KAA2812" prioritetT="HOY_GRU"/>
    </prioritetT>
    <prioritetT kode="HOY_HEL" datoFom="2010-02-13" datoOpprettet="2010-02-13T03:18:01" dekode="Høy" endretAv="KAA2812" erGyldig="true" fagomrade="HEL" opprettetAv="KAA2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" kode="HOY_HEL"/>
        <gsak datoOpprettet="2010-02-13T03:18:01" kode="HOY_HEL"/>
        <ruting datoOpprettet="2010-10-02T05:00:04" prioritetT="HOY_HEL"/>
    </prioritetT>
    <prioritetT kode="HOY_HJE" datoFom="2008-09-16" datoOpprettet="2008-09-16T01:03:58" dekode="Høy" endretAv="kaa2812" erGyldig="true" fagomrade="HJE" opprettetAv="kaa2812" gosys="true" gsak="true" ruting="true">
        <gosys datoOpprettet="2010-10-28T19:36:06" endretAv="KAA2812" kode="HOY_HJE" opprettetAv="KAA2812"/>
